version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pbtl
      POSTGRES_USER: pbtluser
      POSTGRES_PASSWORD: pbtlpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    environment:
      DATABASE_URL: postgres://pbtluser:pbtlpassword@postgres:5432/pbtl
    depends_on:
      - postgres
    user: "root"
    # Command to keep the server running indefinitely
    command: tail -f /dev/null

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
    user: "root"
    # Command to keep the client running indefinitely
    command: tail -f /dev/null

volumes:
  postgres-data:
    driver: local
